version: '3'

services:
  ubuntu:
    build: ./ubuntu
    container_name: minishell
    image: minishell
    platform: 'linux/amd64'
    restart: always
    tty: true
    volumes:
      - ${HOME}:/mnt/host/
