# name: norm

# on:
#   push:

# jobs:
#   steps:
#   - name: 42 Norminette
#   - uses: alexandregv/norminette-action@v3
name: norm
on:
  push:
jobs:
  norminette:
    runs-on: ubuntu-20.04
    steps:
      - run: python3 -m pip install norminette
      - run: norminette -R CheckForbiddenSourceHeader
      - run: norminette -R CheckDefine
      - run: norminette