name: norminette
on: [pull_request, workflow_dispatch]

jobs:
norminette_v3:
  runs-on: ubuntu-20.04
  name: norminette v3
  steps:
  - name: checkout git repository
  - uses: actions/checkout@v3

  - name: install norminette
    run: python3 -m pip install --upgrade pip setuptools
    run: python3 -m pip install norminette

  - name: run norminette
    run: norminette
    run: norminette -R CheckForbiddenSourceHeader
    run: norminette -R CheckDefine
